version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  frontend:
    build:
      context: ./portfolio-frontend
    ports:
      - "3000:80"
    depends_on:
      - рівня
    restart: always